permalinks: title
baseurl: 
map:
 - title: Home
   path: http://localhost:3000
   caption: Discovering Css
 - title: Core
   caption: The workshop content
   subpages:
     - title: Transition
       path:  /core/transition.html
     - title: Animation
       path:  /core/animation.html
     - title: Responsive Design
       path:  /core/responsive.html
     - title: Css for mobile
       path:  /core/mobile.html
     - title: Sass and Less
       path:  /core/sass-less.html  
     - title: Framework Twitter Boostrap
       path:  /core/framework.html
